drop table usuario cascade constraints;
drop table area_risco cascade constraints;
drop table evento cascade constraints;
drop table alerta cascade constraints;
drop table rota_de_fuga cascade constraints;
drop table notificacao cascade constraints;
drop table usu_not cascade constraints;
drop table are_eve cascade constraints;
drop table contato cascade constraints;


create table area_risco (
   id_area_risco    number(5)
      generated by default as identity
      constraint pk_area_risco primary key,
   alcance          number(5,2)
      constraint ar_ri_alcance_nn not null,
   nome_area        varchar(100)
      constraint ar_ri_nome_area not null,
   local_area_risco sdo_geometry
      constraint ar_ri_local_area_risco not null,
   nivel_risco      number(2)
      constraint ar_ri_nivel_risco not null,
   tipo_risco       varchar(40)
      constraint ar_ri_tipo_risco not null
);



create table usuario (
   id_usuario            number(6)
      generated by default as identity
      constraint pk_id_usuario primary key,
   nome_usuario          varchar(100)
      constraint us_nome_nn not null,
   data_cadastro         date default sysdate,
   cpf                   char(11)
      constraint us_cpf_un unique
      constraint us_cpf_nn not null,
   email                 varchar(50)
      constraint us_email_un unique,
   tipo_usuario          varchar(50)
      constraint us_tipo_nn not null,
   telefone              char(11),
   local_usuario         sdo_geometry,
   fk_area_risco_usuario number(5)
      constraint fk_us_area_risco
         references area_risco ( id_area_risco )
);



create table evento (
   id_evento   number(6)
      generated by default as identity
      constraint pk_ev_id primary key,
   acao_tomada varchar(100)
);

create table alerta (
   id_alerta        number(5)
      generated by default as identity
      constraint pk_al_id primary key,
   titulo           varchar(100)
      constraint al_titulo_nn not null,
   descricao        varchar(500)
      constraint al_descricao_nn not null,
   nivel_risco      varchar(20)
      constraint al_nivel_risco_nn not null,
   data_inicio      date default sysdate
      constraint al_data_inicio_nn not null,
   data_fim         date default (sysdate + 4/24)
      constraint al_data_fim_nn not null,
   alerta_criado_em date default sysdate,
   latitude         number(9,6)
      constraint al_latitude_nn not null,
   longitude        number(9,6)
      constraint al_longitude_nn not null,
   uf               varchar(2)
      constraint al_uf_nn not null,
   municipio        varchar(100)
      constraint al_municipio_nn not null,
   fk_usuario       number(6)
      constraint al_fk_usuario_id
         references usuario ( id_usuario )
);

create table rota_de_fuga (
   id_rota            number(6)
      generated by default as identity
      constraint pk_rt_id primary key,
   origem             sdo_geometry
      constraint ro_de_fu_origem_nn not null,
   destino            sdo_geometry
      constraint ro_de_fu_destino_nn not null,
   rota_criado_em     date default sysdate,
   fk_area_risco_rota number(5)
      constraint rt_de_fu_fk_ar_ri
         references area_risco ( id_area_risco )
);

create table notificacao (
   id_notificacao       number(7)
      generated by default as identity
      constraint pk_nt_id primary key,
   mensagem_notificacao varchar(200)
      constraint nt_mensagem_notificacao_nn not null,
   tipo_notificacao     varchar(40)
      constraint nt_tipo_notificacao_nn not null,
   data_envio           date
);

create table usu_not (
   fk_id_notificacao number(7)
      constraint us_no_fk_notificacao
         references notificacao ( id_notificacao ),
   fk_id_usuario     number(6)
      constraint us_no_fk_usuario
         references usuario ( id_usuario )
);

create table are_eve (
   fk_evento_eve number(6)
      constraint ar_ev_fk_evento
         references evento ( id_evento ),
   fk_area_eve   number(5)
      constraint ar_ev_fk_area
         references area_risco ( id_area_risco )
);

create table contato (
   id_contato    number(6)
      generated by default as identity
      constraint pk_contato_id primary key,
   nome          varchar(100)
      constraint cont_nome_nn not null,
   email         varchar(50)
      constraint cont_email_nn not null,
   telefone      char(11)
      constraint cont_telefone_nn not null,
   mensagem      varchar(1000)
      constraint cont_mensagem_nn not null,
   data_envio    date default sysdate
);
